### PR TITLE
Support for ATTiny Processors

### PR DESCRIPTION
**Pull request by gculik**

### CODE REVIEW

**Comment by martin2250** [comment]
Hi Jiri,

looks great, I'll merge it when I have some time on my hands.

Just one quick question: how does this line work:
`uint8_t digitalPin = analog_pin_to_digital_pin + ADCChannel;`

with
```
const uint8_t PROGMEM analog_pin_to_digital_pin[] = {
	5, /* 0 */
	2,
	4,
	3,
	NOT_A_PIN, 
	NOT_A_PIN
};
```
, shouldn't this return a pointer to the value in program space?

Greetings
Martin

**Comment by gculik** [comment]
Yes it should, I fixed the lookup.

**Comment by martin2250** [comment]
Hi, just wanted to let you know that I've not forgotten about your pull request. I just want to test it beforehand which I don't have time for in the next few weeks.
Thanks for being patient

**Comment by gculik** [comment]
No problem.  I just needed it for a project with Adafruit Arduino Gemma, so I figured it would be useful to others.

**Comment by martin2250** [comment]
thanks!

**Pull request merged**
